# -*- coding: utf-8 -*-
"""
.. module:: training.datatypes.loss_batch
   :platform: Linux, Windows, OSX
   :synopsis: EpisodeBatch definition

.. moduleauthor:: AARTLab <danahugh@andrew.cmu.edu>

Definition of a simple datatype for handling a batch of generated losses
during trianing.
"""

import tensorflow as tf
from typing import Mapping

class LossBatch(tf.experimental.ExtensionType):
	"""
	An LossBatch is a data structure class for collecting loss data
	generated by an episode during training.

	Attributes
	----------
	"""

	losses : tf.Tensor
	sublosses : Mapping[str, "LossBatch"] = {}

