# -*- coding: utf-8 -*-
"""
.. module:: training.datatypes.reward_batch
   :platform: Linux, Windows, OSX
   :synopsis: EpisodeBatch definition

.. moduleauthor:: AARTLab <danahugh@andrew.cmu.edu>

Definition of a simple datatype for handling a batch of generated rewards
during trianing.
"""

import tensorflow as tf
from typing import Mapping

class RewardBatch(tf.experimental.ExtensionType):
	"""
	An RewardBatch is a data structure class for collecting reward data
	generated by an episode during training.

	Attributes
	----------
	"""

	rewards : tf.Tensor
	subrewards : Mapping[str, "RewardBatch"] = {}
